import { Membership } from '@/types/membership';

export const membership: Membership = {
  id: 123456,
  firstName: 'John',
  lastName: 'Doe',
  email: 'johndoe@example.com',
  status: 'Active',
  level: 'Premium',
  joinDate: '2011-04-24T00:00:00Z',
  renewalDate: '2024-01-01T00:00:00Z',
  paymentInfo: '**** **** **** 1234',
  wallet: {
    balance: 500,
    transactions: [
      {
        id: 1,
        date: '2022-01-01T00:00:00Z',
        description: 'Initial deposit',
        amount: 500,
      },
      {
        id: 2,
        date: '2022-02-01T00:00:00Z',
        description: 'Monthly membership fee',
        amount: -50,
      },
      {
        id: 3,
        date: '2022-03-01T00:00:00Z',
        description: 'Purchase of merchandise',
        amount: -25,
      },
      {
        id: 4,
        date: '2022-04-01T00:00:00Z',
        description: 'Refund for cancelled event',
        amount: 75,
      },
    ],
  },
};

export const members = [
  {
    id: 1,
    firstName: 'John',
    lastName: 'Doe',
    level: 'Gold',
    position: 'Manager',
    occupation: 'Marketing',
    email: 'john.doe@example.com',
    phone: '123-456-7890',
    gender: 'Male',
    status: 'Active',
    picture: '/images/hero.webp',
  },
  {
    id: 2,
    firstName: 'Jane',
    lastName: 'Doe',
    level: 'Silver',
    position: 'Supervisor',
    occupation: 'Sales',
    email: 'jane.doe@example.com',
    phone: '123-456-7891',
    gender: 'Female',
    status: 'Inactive',
    picture: '/images/image1.jpg',
  },
  {
    id: 3,
    firstName: 'Bob',
    lastName: 'Smith',
    level: 'Bronze',
    position: 'Coordinator',
    occupation: 'HR',
    email: 'bob.smith@example.com',
    phone: '123-456-7892',
    gender: 'Male',
    status: 'Active',
    picture: '/images/image2.jpg',
  },
  {
    id: 4,
    firstName: 'Alice',
    lastName: 'Johnson',
    level: 'Platinum',
    position: 'Director',
    occupation: 'Finance',
    email: 'alice.johnson@example.com',
    phone: '123-456-7893',
    gender: 'Female',
    status: 'Active',
    picture: '/images/image3.jpg',
  },
];
